#!/usr/bin/env bash
# =============================================================================
#  BDA-P2  —  Large-Scale Data Engineering & Algorithmic Trading (P1 + P2)
#
#  USAGE
#    ./run_full_pipeline.sh <command>
#
#  COMMANDS
#    all | pipeline   Full safe pipeline (ingest -> backtest -> simulated bot)
#    verify           Check the large artefacts are real (not Git-LFS stubs)
#    ingest           Landing Zone ingestion
#    format           Formatted Zone standardization
#    trusted          Trusted Zone data quality
#    preprocess       Formatted + Trusted via the bundled orchestrator
#    test             Run all unit tests
#    graphs           Exploitation Zone graph generation
#    analyze          SPARQL analytical inferences
#    classify         Baseline MLP + RandomForest classifiers
#    train            RETRAIN embeddings + ensemble (OVERWRITES best_model.pkl)
#    backtest         Out-of-sample backtest, 10 bps friction (news-aware)
#    bot-dry          Trading bot, simulated, no orders
#    bot-live         Trading bot, LIVE high_alpha (real orders; asks confirm)
#    bot-prod         Trading bot, LIVE full-universe top-K (real orders)
# =============================================================================

set -euo pipefail

# Always operate from the repo root (this script's directory).
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

# ----------------------------------------------------------------------------
# Detect the Python launcher (macOS usually "python3", Windows "python").
# ----------------------------------------------------------------------------
detect_python() {
    if command -v python3 >/dev/null 2>&1; then
        PY="python3"
    elif command -v python >/dev/null 2>&1; then
        PY="python"
    else
        echo "ERROR: neither 'python3' nor 'python' found on PATH." >&2
        echo "Install Python 3 and make sure it is on your PATH, then retry." >&2
        exit 1
    fi
}

# Echo a command, then run it.
run() {
    echo ""
    echo ">>> $*"
    "$@"
}

# For commands that need a shell-level env-var prefix (PYTHONPATH=...).
run_sh() {
    echo ""
    echo ">>> $1"
    bash -c "$1"
}

# ============================================================================
#  COMMANDS
# ============================================================================

# ---- Sanity check: are the big artefacts real, or Git-LFS pointer stubs? ----
cmd_verify() {
    echo "Checking large artefacts (these must NOT be tiny):"
    local missing=0
    for f in ExploitationZone/best_model.pkl \
             ExploitationZone/financial_knowledge_graph.ttl; do
        if [ ! -f "$f" ]; then
            echo "  [MISSING] $f"
            missing=1
            continue
        fi
        # wc -c is portable across macOS and Git Bash.
        local bytes
        bytes=$(wc -c < "$f" | tr -d ' ')
        if [ "$bytes" -lt 100000 ]; then
            echo "  [STUB?]   $f  ($bytes bytes) -- looks like a Git-LFS pointer, not the real file"
            missing=1
        else
            echo "  [OK]      $f  ($bytes bytes)"
        fi
    done
    if [ "$missing" -ne 0 ]; then
        echo ""
        echo "WARNING: one or more large artefacts are missing or look like LFS stubs."
        echo "Steps that load them (graphs / train / bot) may fail until the real"
        echo "files are restored. They can be regenerated by running 'graphs' and 'train'."
    fi
}

# ---- Step 1: Landing Zone ingestion ----------------------------------------
cmd_ingest() {
    run "$PY" LandingZone/nasdaq.py
    run "$PY" LandingZone/company_history.py
    run "$PY" LandingZone/exchange.py
    run "$PY" LandingZone/additional_information.py
    run "$PY" LandingZone/acquisitions.py
}

# ---- Step 2: Formatted Zone standardization --------------------------------
cmd_format() {
    run "$PY" FormattedZone/formatted_zone_pipeline.py
}

# ---- Step 3: Trusted Zone data quality -------------------------------------
cmd_trusted() {
    run "$PY" TrustedZone/dataQuality.py
}

# ---- Steps 2-4 combined via the bundled orchestrator -----------------------
cmd_preprocess() {
    run "$PY" run_preprocessing.py
}

# ---- All unit tests --------------------------------------------------------
cmd_test() {
    run "$PY" -m pytest FormattedZone/test_formatted_zone_pipeline.py -v
    run "$PY" -m pytest TrustedZone/test_dataQuality.py -v
    run "$PY" -m pytest ExploitationZone/test_macroeconomic_graph.py -v
}

# ---- Step 4: Exploitation Zone graph generation ----------------------------
cmd_graphs() {
    run "$PY" ExploitationZone/data_integration.py
    run "$PY" ExploitationZone/graph_generation.py
    run "$PY" ExploitationZone/geopolitical_macroeconomic.py
}

# ---- Step 5: SPARQL analytical inferences ----------------------------------
#  Note: the ARIMA scripts referenced in the README are not part of this
#  bundle, so only the SPARQL analysis is run here.
cmd_analyze() {
    run "$PY" DataAnalysisPipeline1/sparql_analysis.py
}

# ---- Baseline classifiers (MLP + RandomForest) -----------------------------
cmd_classify() {
    run "$PY" DataAnalysisPipeline2/scripts/stock_prediction_mlp.py
    run "$PY" DataAnalysisPipeline2/scripts/stock_prediction_random_forest.py
}

# ---- Step 6: Retrain embeddings + ensemble ---------------------------------
#  WARNING: this overwrites the delivered ExploitationZone/best_model.pkl. We
#  back it up first, and reproduce the *news-trained* model (USE_NEWS_FEATURES=1,
#  using the shipped ExploitationZone/news_features.parquet) so the regenerated
#  model stays consistent with the news-aware backtest and the live bot.
cmd_train() {
    echo ""
    echo "NOTE: 'train' RETRAINS and overwrites ExploitationZone/best_model.pkl"
    echo "      (the delivered ~46MB model). A timestamped backup is made first."
    if [ -f ExploitationZone/best_model.pkl ]; then
        cp ExploitationZone/best_model.pkl \
           "ExploitationZone/best_model.pkl.bak.$(date +%Y%m%d_%H%M%S)"
    fi
    run_sh "USE_NEWS_FEATURES=1 $PY DataAnalysisPipeline2/scripts/kg_embeddings_classifier.py"
}

# ---- Step 7: Out-of-sample backtest (10 bps friction) ----------------------
#  The deployed best_model.pkl carries point-in-time news_* features, so we run
#  the news-aware verifier. (verify_hmm_kalman_horizons.py and
#  verify_subsets_comparison.py are NOT news-aware and would KeyError on the
#  news columns; run them only against a news-free model.)
cmd_backtest() {
    run_sh "PYTHONPATH=DataAnalysisPipeline2/scripts $PY DataAnalysisPipeline2/scripts/backtests/verify_unseen_out_of_sample.py"
}

# ---- Step 8: Trading bot ----------------------------------------------------
cmd_bot_dry() {
    run "$PY" -m DataAnalysisPipeline2.trading_agent.run \
        --universe high_alpha --strategy high_confidence
}

confirm_live() {
    echo ""
    echo "!!! WARNING: this places REAL orders on Alpaca and requires .env credentials."
    printf "Type 'I UNDERSTAND' to continue: "
    read -r reply
    if [ "$reply" != "I UNDERSTAND" ]; then
        echo "Aborted."
        exit 1
    fi
}

cmd_bot_live() {
    confirm_live
    run "$PY" -m DataAnalysisPipeline2.trading_agent.run \
        --universe high_alpha --strategy high_confidence --live
}

cmd_bot_prod() {
    confirm_live
    run "$PY" -m DataAnalysisPipeline2.trading_agent.run \
        --universe full --strategy top_k --top-pct 5 --top-k 10 --live
}

# ---- Full safe pipeline (no live trading) ----------------------------------
#  Uses the delivered ExploitationZone/best_model.pkl as-is; model (re)training
#  is the separate, destructive 'train' step and is intentionally NOT part of
#  'all', so a full run cannot silently overwrite the shipped model.
cmd_pipeline() {
    cmd_verify
    cmd_ingest
    cmd_format
    cmd_trusted
    cmd_test
    cmd_graphs
    cmd_analyze
    cmd_classify
    cmd_backtest
    cmd_bot_dry
    echo ""
    echo "=== Full pipeline complete (ingest -> backtest -> simulated bot run). ==="
    echo "    Note: 'all' uses the shipped best_model.pkl; run 'train' separately"
    echo "    (destructive) to regenerate it."
}

usage() {
    grep -E '^#( |$)' "$0" | sed -E 's/^# ?//'
    exit 1
}

# ============================================================================
#  DISPATCH
# ============================================================================
main() {
    detect_python

    local cmd="${1:-}"
    case "$cmd" in
        verify)       cmd_verify ;;
        ingest)       cmd_ingest ;;
        format)       cmd_format ;;
        trusted)      cmd_trusted ;;
        preprocess)   cmd_preprocess ;;
        test)         cmd_test ;;
        graphs)       cmd_graphs ;;
        analyze)      cmd_analyze ;;
        classify)     cmd_classify ;;
        train)        cmd_train ;;
        backtest)     cmd_backtest ;;
        bot-dry)      cmd_bot_dry ;;
        bot-live)     cmd_bot_live ;;
        bot-prod)     cmd_bot_prod ;;
        pipeline|all) cmd_pipeline ;;
        ""|-h|--help|help) usage ;;
        *) echo "Unknown command: $cmd" >&2; echo ""; usage ;;
    esac
}

main "$@"
